import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Video, Mail, Github } from 'lucide-react';
/**
 * Global footer displayed on all pages.
 * Matches the dark layout with brand, navigation, features and contact.
 *
 * @returns {JSX.Element} Site footer with sitemap and project details.
 */
export function AppFooter() {
    return (_jsx("footer", { className: "site-footer", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "footer-top", children: [_jsxs("section", { className: "footer-brand", "aria-label": "Informaci\u00F3n de VideoMeet", children: [_jsxs("div", { className: "footer-brand-title", children: [_jsx("span", { className: "footer-brand-icon", "aria-hidden": "true", children: _jsx(Video, { className: "brand-icon-svg", "aria-hidden": "true" }) }), _jsx("span", { children: "VideoMeet" })] }), _jsx("p", { children: "Plataforma profesional de videoconferencia para colaboraci\u00F3n remota sin interrupciones." })] }), _jsxs("section", { "aria-label": "Navegaci\u00F3n principal", children: [_jsx("h3", { className: "footer-title", children: "Navegaci\u00F3n" }), _jsxs("ul", { className: "footer-list", children: [_jsx("li", { children: _jsx(Link, { className: "footer-link", to: "/", children: "Inicio" }) }), _jsx("li", { children: _jsx(Link, { className: "footer-link", to: "/about", children: "Sobre nosotros" }) }), _jsx("li", { children: _jsx(Link, { className: "footer-link", to: "/meetings/new", children: "Panel" }) }), _jsx("li", { children: _jsx(Link, { className: "footer-link", to: "/account", children: "Perfil" }) })] })] }), _jsxs("section", { "aria-label": "Funcionalidades principales", children: [_jsx("h3", { className: "footer-title", children: "Funcionalidades" }), _jsxs("ul", { className: "footer-list", children: [_jsx("li", { children: "Videoconferencia" }), _jsx("li", { children: "Chat en Tiempo Real" }), _jsx("li", { children: "Comunicaci\u00F3n por Voz" }), _jsx("li", { children: "Compartir Pantalla" }), _jsx("li", { children: _jsx(Link, { className: "footer-link", to: "/sitemap", children: "Mapa del Sitio" }) })] })] }), _jsxs("section", { "aria-label": "Informaci\u00F3n de contacto", children: [_jsx("h3", { className: "footer-title", children: "Conectar" }), _jsxs("ul", { className: "footer-list", children: [_jsx("li", { children: _jsxs("a", { className: "footer-link footer-link-email", href: "mailto:support@conferencehub.com", children: [_jsx(Mail, { className: "footer-icon", "aria-hidden": "true" }), _jsx("span", { children: "support@conferencehub.com" })] }) }), _jsx("li", { children: _jsx("div", { className: "footer-socials", "aria-label": "Redes sociales", children: _jsx("a", { href: "https://github.com", className: "footer-social-link", "aria-label": "GitHub", target: "_blank", rel: "noreferrer", children: _jsx(Github, { className: "footer-icon", "aria-hidden": "true" }) }) }) })] })] })] }), _jsx("div", { className: "footer-bottom", children: "\u00A9 2025 VideoMeet. Todos los derechos reservados." })] }) }));
}
